:scheduler:
  :schedule:
    expire_subscriptions:
      cron: "0 * * * * *"
      class: Espago::ExpireSubscriptionJob
      queue: default
    auto_renew_subscriptions:
      cron: "0 * * * * *"
      class: Espago::AutoRenewSubscriptionJob
      queue: default